version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: beeq-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beeq
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: beeq-redis
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: beeq-rabbitmq
    restart: always
    ports:
      - '5672:5672' # Port AMQP
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  api:
    build: .
    container_name: beeq-api
    command: 'npm run start:prod' # API
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - rabbitmq
      - redis
    env_file: .env

  worker:
    build: .
    container_name: beeq-worker
    command: 'npm run start:worker' # Worker
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - redis
    env_file: .env

volumes:
  postgres_data:
